coverage:
  status:
    project:
      default:
        # non-blocking checks
        informational: true
        target: auto
        # allow a 1% drop from the previous base commit coverage (for exception handling in download)
        threshold: 1%
    patch:
      default:
        # non-blocking checks
        informational: true
  
ignore:
 - data4co/solver/mis/gurobi.py
 - data4co/solver/tsp/pyconcorde/setup.py
