name: Test Data4CO

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install relatived package
      run: |
        sudo apt-get update
        sudo apt-get install make
        sudo apt-get install cmake
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
    - name: Compile Solvers
      run: |
        python tests/compile_solvers.py
    - name: Test using pytest
      run: |
        pip install pytest
        pytest
    - name: package all the generated files
      uses: actions/upload-artifact@v2
      with:
        name: data4co
        path: |
          data4co/**